[package]
name = "AOC-2015-01"
version = "0.1.0"
authors = ["YearOfDev"]
edition = "2018"

[[bin]]
name = "solution"
path = "solution.rs"

[dependencies]
aoc_utils = { path = "../../../utils/rust/aoc_utils" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"